### ISSUE TITLE
The crate does not work with MacOS versions below 10.11 anymore. 

### ISSUE THREAD

**Issue by nical** [servo/core-graphics-rs#66]
It isn't possible to link against this crate on older macos versions since version 0.4.1 containing a commit around [1d652dd5db9124aba79e4f6292c3b292ee5403d7](https://github.com/servo/core-graphics-rs/commit/1d652dd5db9124aba79e4f6292c3b292ee5403d7) which added a bunch of calls to the CGEvent API. The first symbol that stops working on our CI is CGEventPostToPid (macos 10.11+) but there are probably other missing symbols.

Unfortunately Firefox's WebRender integration needs to compile on macos 10.7.

It would be great to have a cargo feature flag to disable the APIs that are unavailable in 10.7. (Hopefully WebRender does not depend on any of them).

**Comment by nox** [comment]
If we don't actually use them, we should just remove them. Adding them is a breaking change.

**Comment by nical** [comment]
Perhaps @WilsonGiese who contributed these APIs in PR #59 needs them. It's fair to have them conditionally compiled (as long as we have a way to keep WebRender working on 10.7 I'm happy).

**Comment by nox** [comment]
It's fair to keep them if we put them behind a feature flag. The default build still needs to succeed where it did before.

**Comment by jrmuizel** [comment]
FWIW, we only need support back to 10.9

**Comment by jrmuizel** [comment]
Can we get #59 backed out and do a 0.4.4 release?

**Comment by jdm** [comment]
On it.

**Comment by jdm** [comment]
https://github.com/servo/core-graphics-rs/pull/67

**Comment by jdm** [comment]
0.5 has been published, and 0.4.3 has been yanked.

**Comment by WilsonGiese** [comment]
Ah, @nical sorry for breaking your builds! All other symbols are available from 10.4 onwards. Hopefully this didn't cause too much heartache 😕
