### ISSUE TITLE
core-graphics 0.3.2 fails to build on 1.20.0 on OSX

### ISSUE THREAD

**Issue by vvanders** [servo/core-graphics-rs#91]
Seeing this after updating to 1.20.0:

```
...
error: type `private::ffi::CGSRegionObject` is private
  --> /Users/zzz/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.3.2/src/private.rs:81:21
   |
81 |             assert!(ffi::CGSSetSurfaceShape(self.context_id,
   |                     ^^^^^^^^^^^^^^^^^^^^^^^
```

Seems to be impacting data_provider::__CGDataProvider, color_space::__CGColorSpace and private::ffi::CGSRegionObject.

rustup show:
```
active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.20.0 (f3d6973f4 2017-08-27)
```

Let me know if you need any more details, happy to provide it.

**Comment by jdm** [comment]
Why are you using version 0.3.2?

**Comment by vvanders** [comment]
So one of my dependencies pins is. Is there a breaking change that causes this? It compiles fine with 1.19.0.

**Comment by jdm** [comment]
https://github.com/servo/core-graphics-rs/commit/e805130b6bec009bbacedd0646bcb88e717f0e51 is the commit that addressed a long-time warning about private types in public apis that was turned into an error in 1.20.

**Comment by jdm** [comment]
Nevermind, that's unrelated to the code causing an error.

**Comment by jdm** [comment]
Nevermind twice, that commit is indeed solving the issue that you're observing.

**Comment by vvanders** [comment]
Okay cool, thanks for the details and sorry for the incorrect issue. I'll work with the library owner to see if they can move to a newer version.
